use chrono::Local;

/// Templates for generating Obsidian-compatible Markdown files
pub struct Templates;

impl Templates {
    /// Generate session archive frontmatter and content
    pub fn session_archive(
        title: &str,
        date: &str,
        session_id: &str,
        cwd: &str,
        git_branch: Option<&str>,
        duration: Option<&str>,
        tool_calls: usize,
        summary: &str,
        decisions: &str,
        code_changes: &str,
        learnings: &str,
        skill_hints: &str,
    ) -> String {
        let created = Local::now().to_rfc3339();
        let git_branch_str = git_branch.unwrap_or("N/A");
        let duration_str = duration.unwrap_or("N/A");

        format!(
            r#"---
title: "{title}"
date: {date}
session_id: {session_id}
cwd: "{cwd}"
git_branch: "{git_branch_str}"
duration: "{duration_str}"
tool_calls: {tool_calls}
tags: [claude-code, session-archive]
created: {created}
---

# {title}

## Context

- **Working Directory**: `{cwd}`
- **Git Branch**: `{git_branch_str}`
- **Session Duration**: {duration_str}
- **Tool Calls**: {tool_calls}

## Summary

{summary}

## Key Decisions & Trade-offs

{decisions}

## Code Changes

{code_changes}

## Learnings

{learnings}

## Potential Skills/Commands

{skill_hints}

---
*Archived by Daily Context Archive System*
"#
        )
    }

    /// Generate daily summary frontmatter and content
    pub fn daily_summary(
        date: &str,
        sessions: &[String],
        overview: &str,
        session_details: &str,
        insights: &str,
        skills: &str,
        commands: &str,
        reflections: &str,
        tomorrow_focus: &str,
    ) -> String {
        let updated = Local::now().to_rfc3339();
        let sessions_yaml: String = sessions
            .iter()
            .map(|s| format!("  - \"{}\"", s))
            .collect::<Vec<_>>()
            .join("\n");
        let total = sessions.len();

        format!(
            r#"---
date: {date}
updated: {updated}
tags: [daily-summary, claude-code]
sessions:
{sessions_yaml}
total_sessions: {total}
---

# Daily Summary - {date}

## Overview

{overview}

## Sessions

{session_details}

## Key Insights

{insights}

## Skills & Commands Identified

### Potential Skills

{skills}

### Potential Commands

{commands}

## Reflections

{reflections}

## Tomorrow's Focus

{tomorrow_focus}

---
*Generated by Daily Context Archive System*
*Last updated: {updated}*
"#
        )
    }

    /// Generate a minimal daily.md for a new day
    pub fn daily_init(date: &str) -> String {
        let created = Local::now().to_rfc3339();

        format!(
            r#"---
date: {date}
created: {created}
updated: {created}
tags: [daily-summary, claude-code]
sessions: []
total_sessions: 0
---

# Daily Summary - {date}

## Overview

_No sessions archived yet._

## Sessions

## Key Insights

## Skills & Commands Identified

### Potential Skills

### Potential Commands

## Reflections

## Tomorrow's Focus

---
*Generated by Daily Context Archive System*
"#
        )
    }

    /// Generate skill template
    pub fn skill(
        name: &str,
        description: &str,
        trigger: &str,
        workflow: &str,
    ) -> String {
        let timestamp = Local::now().to_rfc3339();

        format!(
            r#"---
name: {name}
description: "{description}"
metadata:
  version: 1.0.0
  generated_by: daily
  generated_at: {timestamp}
---

# {name}

{description}

## Trigger

Use this skill when: {trigger}

## Workflow

{workflow}

## Examples

_Add examples based on your usage patterns._

---
*Generated from daily archive insights*
"#
        )
    }

    /// Generate command template
    pub fn command(
        name: &str,
        description: &str,
        use_case: &str,
        content: &str,
    ) -> String {
        format!(
            r#"---
description: "{description}"
---

# {name}

{use_case}

{content}
"#
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_session_archive_template() {
        let content = Templates::session_archive(
            "Test Session",
            "2026-01-16",
            "abc123",
            "/home/user/project",
            Some("main"),
            Some("30 min"),
            10,
            "Test summary",
            "Test decisions",
            "Test changes",
            "Test learnings",
            "Test hints",
        );

        assert!(content.contains("title: \"Test Session\""));
        assert!(content.contains("session_id: abc123"));
        assert!(content.contains("tool_calls: 10"));
    }

    #[test]
    fn test_daily_init_template() {
        let content = Templates::daily_init("2026-01-16");
        assert!(content.contains("date: 2026-01-16"));
        assert!(content.contains("total_sessions: 0"));
    }
}
