use anyhow::Result;
use chrono::Local;
use std::fs;

use crate::config::load_config;
use crate::hooks::read_hook_input;

/// Handle SessionStart hook from Claude Code
/// Creates today's directory if it doesn't exist and initializes daily.md
pub async fn handle() -> Result<()> {
    let config = load_config()?;

    // Check if hooks are enabled
    if !config.hooks.enable_session_start {
        return Ok(());
    }

    // Try to read hook input, but don't fail if not available
    // (allows manual testing without stdin)
    let _input = match read_hook_input() {
        Ok(input) => Some(input),
        Err(_) => None,
    };

    let today = Local::now().format("%Y-%m-%d").to_string();
    let daily_dir = config.today_dir();

    // Create today's directory if first session of the day
    if !daily_dir.exists() {
        fs::create_dir_all(&daily_dir)?;

        // Initialize daily.md with frontmatter
        let daily_md = daily_dir.join("daily.md");
        let now = Local::now();
        let content = format!(
            r#"---
date: {}
created: {}
updated: {}
tags: [daily-summary, claude-code]
sessions: []
total_sessions: 0
---

# Daily Summary - {}

## Overview

_No sessions archived yet._

## Sessions

## Key Insights

## Skills & Commands Identified

## Reflections

---
*Generated by Daily Context Archive System*
"#,
            today,
            now.to_rfc3339(),
            now.to_rfc3339(),
            today
        );
        fs::write(&daily_md, content)?;

        eprintln!("[daily] Created daily directory: {}", daily_dir.display());
    }

    // Exit with 0 to allow session to continue
    Ok(())
}
